version: '3'

services:
    postgres:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        ports:
            - 5432:5432
        volumes:
            - postgresvolume:/var/lib/postgresql/data

volumes:
    postgresvolume: